services:
  redis:
    image: 'redis:6.0-alpine'
    ports:
      - '6379:6379'
  app:
    restart: on-failure
    build: .
    depends_on:
      - redis
    ports:
      - '8080:8080'
    environment:
      REDIS_URL: redis://redis:6379/0
